name: adati
description: "A habit tracker app with timeline visualization."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_riverpod: ^3.0.1
  
  # Navigation & routing
  go_router: ^17.0.0
  
  # Localization & i18n
  easy_localization: ^3.0.7
  
  # Local storage
  shared_preferences: ^2.3.3
  
  # Backend & database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # Environment variables
  flutter_dotenv: ^6.0.0
  
  # UI & animations
  animations: ^2.1.0
  skeletonizer: ^2.1.0+1
  
  # File handling
  file_picker: ^10.3.6
  
  # Logging
  easy_logger: ^0.0.2
  
  # Device info
  package_info_plus: ^9.0.0
  
  # Notifications
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  
  # Date formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
